apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-operators-ibm-db2u-operator
spec:
  destination:
    namespace: cpd-operators
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/cpd-operators/ibm-db2u-operator
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-db2u-operator
    targetRevision: master
    helm:
      releaseName: ibm-db2u-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
