apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-db2u-operator
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-db2u-operator/namespace
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-db2u-operator
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
